//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lench.AdvancedControls.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lench.AdvancedControls.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain Axis.
        /// </summary>
        internal static string AxisEditorWindow_ButtonText_ChainAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_ButtonText_ChainAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller Axis.
        /// </summary>
        internal static string AxisEditorWindow_ButtonText_ControllerAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_ButtonText_ControllerAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Axis.
        /// </summary>
        internal static string AxisEditorWindow_ButtonText_CustomAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_ButtonText_CustomAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Axis.
        /// </summary>
        internal static string AxisEditorWindow_ButtonText_KeyAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_ButtonText_KeyAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Axis.
        /// </summary>
        internal static string AxisEditorWindow_ButtonText_MouseAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_ButtonText_MouseAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new chain axis.
        /// </summary>
        internal static string AxisEditorWindow_DefaultAxisName_NewChainAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_DefaultAxisName_NewChainAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new controller axis.
        /// </summary>
        internal static string AxisEditorWindow_DefaultAxisName_NewControllerAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_DefaultAxisName_NewControllerAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new custom axis.
        /// </summary>
        internal static string AxisEditorWindow_DefaultAxisName_NewCustomAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_DefaultAxisName_NewCustomAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new key axis.
        /// </summary>
        internal static string AxisEditorWindow_DefaultAxisName_NewKeyAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_DefaultAxisName_NewKeyAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new mouse axis.
        /// </summary>
        internal static string AxisEditorWindow_DefaultAxisName_NewMouseAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_DefaultAxisName_NewMouseAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new axis.
        /// </summary>
        internal static string AxisEditorWindow_WindowTitle_CreateNewAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_WindowTitle_CreateNewAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new chain axis.
        /// </summary>
        internal static string AxisEditorWindow_WindowTitle_CreateNewChainAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_WindowTitle_CreateNewChainAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new controller axis.
        /// </summary>
        internal static string AxisEditorWindow_WindowTitle_CreateNewControllerAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_WindowTitle_CreateNewControllerAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new custom axis.
        /// </summary>
        internal static string AxisEditorWindow_WindowTitle_CreateNewCustomAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_WindowTitle_CreateNewCustomAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new key axis.
        /// </summary>
        internal static string AxisEditorWindow_WindowTitle_CreateNewKeyAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_WindowTitle_CreateNewKeyAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new mouse axis.
        /// </summary>
        internal static string AxisEditorWindow_WindowTitle_CreateNewMouseAxis {
            get {
                return ResourceManager.GetString("AxisEditorWindow_WindowTitle_CreateNewMouseAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        internal static string AxisEditorWindow_WindowTitle_Edit {
            get {
                return ResourceManager.GetString("AxisEditorWindow_WindowTitle_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCALLY SAVED AXES.
        /// </summary>
        internal static string AxisSelector_Label_LocallySavedAxes {
            get {
                return ResourceManager.GetString("AxisSelector_Label_LocallySavedAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MACHINE EMBEDDED AXES.
        /// </summary>
        internal static string AxisSelector_Label_MachineEmbeddedAxes {
            get {
                return ResourceManager.GetString("AxisSelector_Label_MachineEmbeddedAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select axis.
        /// </summary>
        internal static string AxisSelector_WindowTitle_SelectAxis {
            get {
                return ResourceManager.GetString("AxisSelector_WindowTitle_SelectAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string AxisStatus_Error {
            get {
                return ResourceManager.GetString("AxisStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO LINK.
        /// </summary>
        internal static string AxisStatus_NoLink {
            get {
                return ResourceManager.GetString("AxisStatus_NoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT AVAILABLE.
        /// </summary>
        internal static string AxisStatus_NotAvailable {
            get {
                return ResourceManager.GetString("AxisStatus_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT CONNECTED.
        /// </summary>
        internal static string AxisStatus_NotConnected {
            get {
                return ResourceManager.GetString("AxisStatus_NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT FOUND.
        /// </summary>
        internal static string AxisStatus_NotFound {
            get {
                return ResourceManager.GetString("AxisStatus_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT RUNNING.
        /// </summary>
        internal static string AxisStatus_NotRunning {
            get {
                return ResourceManager.GetString("AxisStatus_NotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AxisStatus_Ok {
            get {
                return ResourceManager.GetString("AxisStatus_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNKNOWN.
        /// </summary>
        internal static string AxisStatus_Unknown {
            get {
                return ResourceManager.GetString("AxisStatus_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        internal static string ButtonText_ArrowNext {
            get {
                return ResourceManager.GetString("ButtonText_ArrowNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        internal static string ButtonText_ArrowPrevious {
            get {
                return ResourceManager.GetString("ButtonText_ArrowPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ×.
        /// </summary>
        internal static string ButtonText_Close {
            get {
                return ResourceManager.GetString("ButtonText_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✎.
        /// </summary>
        internal static string ButtonText_EditAxis {
            get {
                return ResourceManager.GetString("ButtonText_EditAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string ButtonText_Help {
            get {
                return ResourceManager.GetString("ButtonText_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ButtonText_Save {
            get {
                return ResourceManager.GetString("ButtonText_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Input Axis.
        /// </summary>
        internal static string ButtonText_SelectInputAxis {
            get {
                return ResourceManager.GetString("ButtonText_SelectInputAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/lench4991/AdvancedControlsMod/wiki/Chain-Axis.
        /// </summary>
        internal static string ChainAxisEditor_HelpURL {
            get {
                return ResourceManager.GetString("ChainAxisEditor_HelpURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chain cycle error.
        /// </summary>
        internal static string ChainAxisEditor_Message_ChainCycleError {
            get {
                return ResourceManager.GetString("ChainAxisEditor_Message_ChainCycleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming this axis formed a cycle in the chain.
        ///.
        /// </summary>
        internal static string ChainAxisEditor_Message_ChainCycleErrorDetail {
            get {
                return ResourceManager.GetString("ChainAxisEditor_Message_ChainCycleErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is already in the axis chain.
        ///Linking it here would create a cycle..
        /// </summary>
        internal static string ChainAxisEditor_Message_ChainCycleErrorDetail2 {
            get {
                return ResourceManager.GetString("ChainAxisEditor_Message_ChainCycleErrorDetail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has been unlinked. .
        /// </summary>
        internal static string ChainAxisEditor_Message_ChainCycleErrorEffect {
            get {
                return ResourceManager.GetString("ChainAxisEditor_Message_ChainCycleErrorEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string ChainMethod_Average {
            get {
                return ResourceManager.GetString("ChainMethod_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string ChainMethod_Maximum {
            get {
                return ResourceManager.GetString("ChainMethod_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string ChainMethod_Minimum {
            get {
                return ResourceManager.GetString("ChainMethod_Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply.
        /// </summary>
        internal static string ChainMethod_Multiply {
            get {
                return ResourceManager.GetString("ChainMethod_Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract.
        /// </summary>
        internal static string ChainMethod_Subtract {
            get {
                return ResourceManager.GetString("ChainMethod_Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string ChainMethod_Sum {
            get {
                return ResourceManager.GetString("ChainMethod_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter &apos;acm&apos; for all available configuration commands..
        /// </summary>
        internal static string Console_Acm_AllAvailable {
            get {
                return ResourceManager.GetString("Console_Acm_AllAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available commands:
        ///  acm modupdate check  	 Checks for mod update.
        ///  acm modupdate enable 	 Enables update checker.
        ///  acm modupdate disable	 Disables update checker.
        ///  acm dbupdate check   	 Checks for controller database update.
        ///  acm dbupdate enable  	 Enables automatic controller database updates.
        ///  acm dbupdate disable 	 Disables automatic controller database updates.
        ///.
        /// </summary>
        internal static string Console_Acm_AllAvailableList {
            get {
                return ResourceManager.GetString("Console_Acm_AllAvailableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for controller DB updates ....
        /// </summary>
        internal static string Console_Acm_CheckingForControllerDBUpdates {
            get {
                return ResourceManager.GetString("Console_Acm_CheckingForControllerDBUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for mod updates ....
        /// </summary>
        internal static string Console_Acm_CheckingForModUpdates {
            get {
                return ResourceManager.GetString("Console_Acm_CheckingForModUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller DB update checker disabled..
        /// </summary>
        internal static string Console_Acm_ControllerDBUpdateCheckerDisabled {
            get {
                return ResourceManager.GetString("Console_Acm_ControllerDBUpdateCheckerDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller DB update checker enabled..
        /// </summary>
        internal static string Console_Acm_ControllerDBUpdateCheckerEnabled {
            get {
                return ResourceManager.GetString("Console_Acm_ControllerDBUpdateCheckerEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command. Enter &apos;acm&apos; for all available commands..
        /// </summary>
        internal static string Console_Acm_InvalidCommand {
            get {
                return ResourceManager.GetString("Console_Acm_InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod update checker disabled..
        /// </summary>
        internal static string Console_Acm_ModUpdateCheckerDisabled {
            get {
                return ResourceManager.GetString("Console_Acm_ModUpdateCheckerDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod update checker enabled..
        /// </summary>
        internal static string Console_Acm_ModUpdateCheckerEnabled {
            get {
                return ResourceManager.GetString("Console_Acm_ModUpdateCheckerEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid argument [check/enable/disable]. Enter &apos;acm&apos; for all available commands..
        /// </summary>
        internal static string Console_Acm_UpdateInvalidArgument {
            get {
                return ResourceManager.GetString("Console_Acm_UpdateInvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing argument [check/enable/disable]. Enter &apos;acm&apos; for all available commands..
        /// </summary>
        internal static string Console_Acm_UpdateMissingArgument {
            get {
                return ResourceManager.GetString("Console_Acm_UpdateMissingArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter &apos;controller&apos; for all available controller commands..
        /// </summary>
        internal static string Console_Controller_AllAvailable {
            get {
                return ResourceManager.GetString("Console_Controller_AllAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available commands:
        ///  controller list		List all connected devices.
        ///  controller info [index]	Show info of a device at index.
        ///.
        /// </summary>
        internal static string Console_Controller_AllAvailableList {
            get {
                return ResourceManager.GetString("Console_Controller_AllAvailableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller list:
        ///.
        /// </summary>
        internal static string Console_Controller_ControllerList {
            get {
                return ResourceManager.GetString("Console_Controller_ControllerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        internal static string Console_Controller_ControllerTag {
            get {
                return ResourceManager.GetString("Console_Controller_ControllerTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID: .
        /// </summary>
        internal static string Console_Controller_GUID {
            get {
                return ResourceManager.GetString("Console_Controller_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command. Enter &apos;controller&apos; for all available commands..
        /// </summary>
        internal static string Console_Controller_InvalidCommand {
            get {
                return ResourceManager.GetString("Console_Controller_InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick.
        /// </summary>
        internal static string Console_Controller_JoystickTag {
            get {
                return ResourceManager.GetString("Console_Controller_JoystickTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices connected..
        /// </summary>
        internal static string Console_Controller_NoDevicesConnected {
            get {
                return ResourceManager.GetString("Console_Controller_NoDevicesConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axis {0}.
        /// </summary>
        internal static string Controller_AxisName_Default {
            get {
                return ResourceManager.GetString("Controller_AxisName_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Trigger.
        /// </summary>
        internal static string Controller_AxisName_LeftTrigger {
            get {
                return ResourceManager.GetString("Controller_AxisName_LeftTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left X.
        /// </summary>
        internal static string Controller_AxisName_LeftX {
            get {
                return ResourceManager.GetString("Controller_AxisName_LeftX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Y.
        /// </summary>
        internal static string Controller_AxisName_LeftY {
            get {
                return ResourceManager.GetString("Controller_AxisName_LeftY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Trigger.
        /// </summary>
        internal static string Controller_AxisName_RightTrigger {
            get {
                return ResourceManager.GetString("Controller_AxisName_RightTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right X.
        /// </summary>
        internal static string Controller_AxisName_RightX {
            get {
                return ResourceManager.GetString("Controller_AxisName_RightX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Y.
        /// </summary>
        internal static string Controller_AxisName_RightY {
            get {
                return ResourceManager.GetString("Controller_AxisName_RightY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown axis.
        /// </summary>
        internal static string Controller_AxisName_UnknownAxis {
            get {
                return ResourceManager.GetString("Controller_AxisName_UnknownAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Axis.
        /// </summary>
        internal static string Controller_AxisName_XAxis {
            get {
                return ResourceManager.GetString("Controller_AxisName_XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Axis.
        /// </summary>
        internal static string Controller_AxisName_YAxis {
            get {
                return ResourceManager.GetString("Controller_AxisName_YAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ball {0}.
        /// </summary>
        internal static string Controller_BallName_Default {
            get {
                return ResourceManager.GetString("Controller_BallName_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown ball.
        /// </summary>
        internal static string Controller_BallName_UnknownBall {
            get {
                return ResourceManager.GetString("Controller_BallName_UnknownBall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Button.
        /// </summary>
        internal static string Controller_ButtonName_AButton {
            get {
                return ResourceManager.GetString("Controller_ButtonName_AButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Button.
        /// </summary>
        internal static string Controller_ButtonName_BackButton {
            get {
                return ResourceManager.GetString("Controller_ButtonName_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B Button.
        /// </summary>
        internal static string Controller_ButtonName_BButton {
            get {
                return ResourceManager.GetString("Controller_ButtonName_BButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button {0}.
        /// </summary>
        internal static string Controller_ButtonName_Default {
            get {
                return ResourceManager.GetString("Controller_ButtonName_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide Button.
        /// </summary>
        internal static string Controller_ButtonName_GuideButton {
            get {
                return ResourceManager.GetString("Controller_ButtonName_GuideButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Shoulder.
        /// </summary>
        internal static string Controller_ButtonName_LeftShoulder {
            get {
                return ResourceManager.GetString("Controller_ButtonName_LeftShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Stick.
        /// </summary>
        internal static string Controller_ButtonName_LeftStick {
            get {
                return ResourceManager.GetString("Controller_ButtonName_LeftStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Shoulder.
        /// </summary>
        internal static string Controller_ButtonName_RightShoulder {
            get {
                return ResourceManager.GetString("Controller_ButtonName_RightShoulder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Stick.
        /// </summary>
        internal static string Controller_ButtonName_RightStick {
            get {
                return ResourceManager.GetString("Controller_ButtonName_RightStick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Button.
        /// </summary>
        internal static string Controller_ButtonName_StartButton {
            get {
                return ResourceManager.GetString("Controller_ButtonName_StartButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown button.
        /// </summary>
        internal static string Controller_ButtonName_UnknownButton {
            get {
                return ResourceManager.GetString("Controller_ButtonName_UnknownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Button.
        /// </summary>
        internal static string Controller_ButtonName_XButton {
            get {
                return ResourceManager.GetString("Controller_ButtonName_XButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Button.
        /// </summary>
        internal static string Controller_ButtonName_YButton {
            get {
                return ResourceManager.GetString("Controller_ButtonName_YButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game controller connected:.
        /// </summary>
        internal static string Controller_GameControllerConnected {
            get {
                return ResourceManager.GetString("Controller_GameControllerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID:.
        /// </summary>
        internal static string Controller_GUID {
            get {
                return ResourceManager.GetString("Controller_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hat {0}.
        /// </summary>
        internal static string Controller_HatName_Default {
            get {
                return ResourceManager.GetString("Controller_HatName_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DPAD.
        /// </summary>
        internal static string Controller_HatName_DPAD {
            get {
                return ResourceManager.GetString("Controller_HatName_DPAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown hat.
        /// </summary>
        internal static string Controller_HatName_UnknownHat {
            get {
                return ResourceManager.GetString("Controller_HatName_UnknownHat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick connected:.
        /// </summary>
        internal static string Controller_JoystickConnected {
            get {
                return ResourceManager.GetString("Controller_JoystickConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string ControllerAxisEditor_AxisX {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_AxisX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string ControllerAxisEditor_AxisY {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_AxisY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another controller.
        /// </summary>
        internal static string ControllerAxisEditor_ButtonText_UseAnotherController {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_ButtonText_UseAnotherController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller axis requires SDL2 library to work.
        ///Press download to install it automatically.
        ///
        ///.
        /// </summary>
        internal static string ControllerAxisEditor_DrawAxis_RequireSDL2Windows {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_DrawAxis_RequireSDL2Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRAG TO SET OFFSET.
        /// </summary>
        internal static string ControllerAxisEditor_Graph_DragToSetOffset {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_Graph_DragToSetOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESET OFFSET.
        /// </summary>
        internal static string ControllerAxisEditor_Graph_ResetOffset {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_Graph_ResetOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/lench4991/AdvancedControlsMod/wiki/Controller-Axis.
        /// </summary>
        internal static string ControllerAxisEditor_HelpURL {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_HelpURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional library needed.
        /// </summary>
        internal static string ControllerAxisEditor_Message_AdditionalLibraryNeeded {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_Message_AdditionalLibraryNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated controller not connected..
        /// </summary>
        internal static string ControllerAxisEditor_Message_AssociatedControllerNotConnected {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_Message_AssociatedControllerNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The device this axis is bound to is not found.
        ///
        ///&lt;b&gt;Device GUID&lt;/b&gt;
        ///.
        /// </summary>
        internal static string ControllerAxisEditor_Message_AssociatedControllerNotConnectedDetail {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_Message_AssociatedControllerNotConnectedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No controllers connected..
        /// </summary>
        internal static string ControllerAxisEditor_Message_NoControllersConnected {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_Message_NoControllersConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect a joystick or controller to use this axis..
        /// </summary>
        internal static string ControllerAxisEditor_Message_NoControllersConnectedDetail {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_Message_NoControllersConnectedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform.
        /// </summary>
        internal static string ControllerAxisEditor_Message_Platform {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_Message_Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are using some other operating system,
        ///download the correct version of the mod..
        /// </summary>
        internal static string ControllerAxisEditor_Message_PlatformCorrect {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_Message_PlatformCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using Linux version of ACM.
        ///.
        /// </summary>
        internal static string ControllerAxisEditor_Message_PlatformLinux {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_Message_PlatformLinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using OSX version of ACM.
        ///.
        /// </summary>
        internal static string ControllerAxisEditor_Message_PlatformOSX {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_Message_PlatformOSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are using Windows version of ACM.
        ///.
        /// </summary>
        internal static string ControllerAxisEditor_Message_PlatformWindows {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_Message_PlatformWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller axis requires SDL2 library to work.
        ///Run the command below to install it.
        ///
        ///.
        /// </summary>
        internal static string ControllerAxisEditor_Message_RequireSDL2Linux {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_Message_RequireSDL2Linux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller axis requires SDL2 library to work.
        ///Download it at the link below.
        ///
        ///.
        /// </summary>
        internal static string ControllerAxisEditor_Message_RequireSDL2OSX {
            get {
                return ResourceManager.GetString("ControllerAxisEditor_Message_RequireSDL2OSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVERVIEW.
        /// </summary>
        internal static string ControlMapper_ButtonText_Overview {
            get {
                return ResourceManager.GetString("ControlMapper_ButtonText_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This block has no available controls..
        /// </summary>
        internal static string ControlMapper_Message_NoAvailableControls {
            get {
                return ResourceManager.GetString("ControlMapper_Message_NoAvailableControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Controls.
        /// </summary>
        internal static string ControlMapper_WindowTitle_AdvancedControls {
            get {
                return ResourceManager.GetString("ControlMapper_WindowTitle_AdvancedControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANGLE.
        /// </summary>
        internal static string ControlName_Angle {
            get {
                return ResourceManager.GetString("ControlName_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTROL.
        /// </summary>
        internal static string ControlName_Default {
            get {
                return ResourceManager.GetString("ControlName_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INPUT.
        /// </summary>
        internal static string ControlName_Input {
            get {
                return ResourceManager.GetString("ControlName_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSITION.
        /// </summary>
        internal static string ControlName_Position {
            get {
                return ResourceManager.GetString("ControlName_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/lench4991/AdvancedControlsMod/wiki/Sharing.
        /// </summary>
        internal static string ControlOverview_HelpURL {
            get {
                return ResourceManager.GetString("ControlOverview_HelpURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; uses no advanced controls..
        /// </summary>
        internal static string ControlOverview_Label_NoControls {
            get {
                return ResourceManager.GetString("ControlOverview_Label_NoControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{0}&lt;/b&gt; for {1}.
        /// </summary>
        internal static string ControlOverview_List_Entry {
            get {
                return ResourceManager.GetString("ControlOverview_List_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use this machine as intended,
        ///make sure all axes report no problems.
        ///
        ///&lt;b&gt;{0}&lt;/b&gt; uses these input axes:.
        /// </summary>
        internal static string ControlOverview_Message_IntroNote {
            get {
                return ResourceManager.GetString("ControlOverview_Message_IntroNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string ControlOverview_WindowTitle {
            get {
                return ResourceManager.GetString("ControlOverview_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string CustomAxisEditor_ButtonText_Start {
            get {
                return ResourceManager.GetString("CustomAxisEditor_ButtonText_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string CustomAxisEditor_ButtonText_Stop {
            get {
                return ResourceManager.GetString("CustomAxisEditor_ButtonText_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File downloaded: .
        /// </summary>
        internal static string CustomAxisEditor_InstallIronPython_FileDownloaded {
            get {
                return ResourceManager.GetString("CustomAxisEditor_InstallIronPython_FileDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Additional library needed&lt;/b&gt;
        ///Custom axis runs on IronPython engine.
        ///Press download to install it automatically..
        /// </summary>
        internal static string CustomAxisEditor_Message_MissingIronPython {
            get {
                return ResourceManager.GetString("CustomAxisEditor_Message_MissingIronPython", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python error.
        /// </summary>
        internal static string CustomAxisEditor_Message_PythonError {
            get {
                return ResourceManager.GetString("CustomAxisEditor_Message_PythonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update code does not return a value..
        /// </summary>
        internal static string CustomAxisEditor_Message_UpdateCodeDoesNotReturnAValue {
            get {
                return ResourceManager.GetString("CustomAxisEditor_Message_UpdateCodeDoesNotReturnAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update code returns {0}
        ///instead of number..
        /// </summary>
        internal static string CustomAxisEditor_Message_UpdateCodeReturnsWrongType {
            get {
                return ResourceManager.GetString("CustomAxisEditor_Message_UpdateCodeReturnsWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        internal static string DownloadButtonText_Complete {
            get {
                return ResourceManager.GetString("DownloadButtonText_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string DownloadButtonText_Download {
            get {
                return ResourceManager.GetString("DownloadButtonText_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DownloadButtonText_Error {
            get {
                return ResourceManager.GetString("DownloadButtonText_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart Besiege.
        /// </summary>
        internal static string DownloadButtonText_Restart {
            get {
                return ResourceManager.GetString("DownloadButtonText_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWN.
        /// </summary>
        internal static string HatButton_Direction_DOWN {
            get {
                return ResourceManager.GetString("HatButton_Direction_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEFT.
        /// </summary>
        internal static string HatButton_Direction_LEFT {
            get {
                return ResourceManager.GetString("HatButton_Direction_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RIGHT.
        /// </summary>
        internal static string HatButton_Direction_RIGHT {
            get {
                return ResourceManager.GetString("HatButton_Direction_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UP.
        /// </summary>
        internal static string HatButton_Direction_UP {
            get {
                return ResourceManager.GetString("HatButton_Direction_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading a button:.
        /// </summary>
        internal static string KeyAxis_ParseButtonID_ErrorWhileLoadingAButton {
            get {
                return ResourceManager.GetString("KeyAxis_ParseButtonID_ErrorWhileLoadingAButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/lench4991/AdvancedControlsMod/wiki/Key-Axes.
        /// </summary>
        internal static string KeyAxisEditor_HelpURL {
            get {
                return ResourceManager.GetString("KeyAxisEditor_HelpURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device disconnected.
        /// </summary>
        internal static string KeyAxisEditor_Message_DeviceDisconnected {
            get {
                return ResourceManager.GetString("KeyAxisEditor_Message_DeviceDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&apos;{0}&apos; is not connected..
        /// </summary>
        internal static string KeyAxisEditor_Message_DeviceDisconnectedDetail {
            get {
                return ResourceManager.GetString("KeyAxisEditor_Message_DeviceDisconnectedDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string KeyAxisEditor_NoBind {
            get {
                return ResourceManager.GetString("KeyAxisEditor_NoBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string Label_Center {
            get {
                return ResourceManager.GetString("Label_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curvaure.
        /// </summary>
        internal static string Label_Curvaure {
            get {
                return ResourceManager.GetString("Label_Curvaure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadzone.
        /// </summary>
        internal static string Label_Deadzone {
            get {
                return ResourceManager.GetString("Label_Deadzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravity.
        /// </summary>
        internal static string Label_Gravity {
            get {
                return ResourceManager.GetString("Label_Gravity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialisation code.
        /// </summary>
        internal static string Label_InitialisationCode {
            get {
                return ResourceManager.GetString("Label_InitialisationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        internal static string Label_Invert {
            get {
                return ResourceManager.GetString("Label_Invert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked axes.
        /// </summary>
        internal static string Label_LinkedAxes {
            get {
                return ResourceManager.GetString("Label_LinkedAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Momentum.
        /// </summary>
        internal static string Label_Momentum {
            get {
                return ResourceManager.GetString("Label_Momentum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string Label_Range {
            get {
                return ResourceManager.GetString("Label_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw.
        /// </summary>
        internal static string Label_Raw {
            get {
                return ResourceManager.GetString("Label_Raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run in global scope.
        /// </summary>
        internal static string Label_RunInGlobalScope {
            get {
                return ResourceManager.GetString("Label_RunInGlobalScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensitivity.
        /// </summary>
        internal static string Label_Sensitivity {
            get {
                return ResourceManager.GetString("Label_Sensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth.
        /// </summary>
        internal static string Label_Smooth {
            get {
                return ResourceManager.GetString("Label_Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snap.
        /// </summary>
        internal static string Label_Snap {
            get {
                return ResourceManager.GetString("Label_Snap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update code.
        /// </summary>
        internal static string Label_UpdateCode {
            get {
                return ResourceManager.GetString("Label_UpdateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading saved axes:.
        /// </summary>
        internal static string Log_AxisLoadingError {
            get {
                return ResourceManager.GetString("Log_AxisLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving axes:.
        /// </summary>
        internal static string Log_AxisSavingError {
            get {
                return ResourceManager.GetString("Log_AxisSavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading machine&apos;s controls:.
        /// </summary>
        internal static string Log_ControlLoadingError {
            get {
                return ResourceManager.GetString("Log_ControlLoadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving machine&apos;s controls..
        /// </summary>
        internal static string Log_ControlSavingError {
            get {
                return ResourceManager.GetString("Log_ControlSavingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDL_GAMECONTROLLERCONFIG environment variable not retrieved..
        /// </summary>
        internal static string Log_EnvVarError {
            get {
                return ResourceManager.GetString("Log_EnvVarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully read SDL_GAMECONTROLLERCONFIG environment variable..
        /// </summary>
        internal static string Log_EnvVarRead {
            get {
                return ResourceManager.GetString("Log_EnvVarRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDL_GAMECONTROLLERCONFIG environment variable not set..
        /// </summary>
        internal static string Log_EnvVarSet {
            get {
                return ResourceManager.GetString("Log_EnvVarSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error downloading file:.
        /// </summary>
        internal static string Log_ErrorDownloadingFile {
            get {
                return ResourceManager.GetString("Log_ErrorDownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Controller DB downloaded..
        /// </summary>
        internal static string Log_GameControllerDBDownloaded {
            get {
                return ResourceManager.GetString("Log_GameControllerDBDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Controller DB is up to date..
        /// </summary>
        internal static string Log_GameControllerDBIsUpToDate {
            get {
                return ResourceManager.GetString("Log_GameControllerDBIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Controller DB update successfull..
        /// </summary>
        internal static string Log_GameControllerDBUpdateSuccessfull {
            get {
                return ResourceManager.GetString("Log_GameControllerDBUpdateSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod is up to date..
        /// </summary>
        internal static string Log_ModIsUpToDate {
            get {
                return ResourceManager.GetString("Log_ModIsUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File downloaded:.
        /// </summary>
        internal static string Log_SuccessDownloadingFile {
            get {
                return ResourceManager.GetString("Log_SuccessDownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect..
        /// </summary>
        internal static string Log_UnableToConnect {
            get {
                return ResourceManager.GetString("Log_UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available:.
        /// </summary>
        internal static string Log_UpdateAvailable {
            get {
                return ResourceManager.GetString("Log_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was saved with mod version {1}.
        ///	It may not be compatible with some newer features..
        /// </summary>
        internal static string Log_VersionWarning {
            get {
                return ResourceManager.GetString("Log_VersionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/lench4991/AdvancedControlsMod/wiki/Mouse-axis.
        /// </summary>
        internal static string MouseAxisEditor_HelpURL {
            get {
                return ResourceManager.GetString("MouseAxisEditor_HelpURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUOYANCY.
        /// </summary>
        internal static string SliderName_Buoyancy {
            get {
                return ResourceManager.GetString("SliderName_Buoyancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISTANCE.
        /// </summary>
        internal static string SliderName_Distance {
            get {
                return ResourceManager.GetString("SliderName_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPLOSIVE CHARGE.
        /// </summary>
        internal static string SliderName_ExplosiveCharge {
            get {
                return ResourceManager.GetString("SliderName_ExplosiveCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLIGHT DURATION.
        /// </summary>
        internal static string SliderName_FlightDuration {
            get {
                return ResourceManager.GetString("SliderName_FlightDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FLYING SPEED.
        /// </summary>
        internal static string SliderName_FlyingSpeed {
            get {
                return ResourceManager.GetString("SliderName_FlyingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEIGHT.
        /// </summary>
        internal static string SliderName_Height {
            get {
                return ResourceManager.GetString("SliderName_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MASS.
        /// </summary>
        internal static string SliderName_Mass {
            get {
                return ResourceManager.GetString("SliderName_Mass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POWER.
        /// </summary>
        internal static string SliderName_Power {
            get {
                return ResourceManager.GetString("SliderName_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANGE.
        /// </summary>
        internal static string SliderName_Range {
            get {
                return ResourceManager.GetString("SliderName_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROTATION.
        /// </summary>
        internal static string SliderName_Rotation {
            get {
                return ResourceManager.GetString("SliderName_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROTATION SPEED.
        /// </summary>
        internal static string SliderName_RotationSpeed {
            get {
                return ResourceManager.GetString("SliderName_RotationSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPEED.
        /// </summary>
        internal static string SliderName_Speed {
            get {
                return ResourceManager.GetString("SliderName_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPRING.
        /// </summary>
        internal static string SliderName_Spring {
            get {
                return ResourceManager.GetString("SliderName_Spring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRENGTH.
        /// </summary>
        internal static string SliderName_Strength {
            get {
                return ResourceManager.GetString("SliderName_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STRING LENGTH.
        /// </summary>
        internal static string SliderName_StringLength {
            get {
                return ResourceManager.GetString("SliderName_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THRUST.
        /// </summary>
        internal static string SliderName_Thrust {
            get {
                return ResourceManager.GetString("SliderName_Thrust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub release page.
        /// </summary>
        internal static string Updater_GithubReleasePageLink {
            get {
                return ResourceManager.GetString("Updater_GithubReleasePageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New update available.
        /// </summary>
        internal static string Updater_NewUpdateAvailable {
            get {
                return ResourceManager.GetString("Updater_NewUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spiderling forum page.
        /// </summary>
        internal static string Updater_SpiderlingForumLink {
            get {
                return ResourceManager.GetString("Updater_SpiderlingForumLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Controls Mod.
        /// </summary>
        internal static string Updater_WindowTitle {
            get {
                return ResourceManager.GetString("Updater_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HORIZONTAL.
        /// </summary>
        internal static string VectorControl_AxisHorizontal {
            get {
                return ResourceManager.GetString("VectorControl_AxisHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POWER.
        /// </summary>
        internal static string VectorControl_AxisPower {
            get {
                return ResourceManager.GetString("VectorControl_AxisPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERTICAL.
        /// </summary>
        internal static string VectorControl_AxisVertical {
            get {
                return ResourceManager.GetString("VectorControl_AxisVertical", resourceCulture);
            }
        }
    }
}
